version: '2.1'

services:
  mysql:
    image: "healthcheck/mysql"
    ports:
      - "3306:3306"
    volumes:
      - ./preseed.sql:/docker-entrypoint-initdb.d/preseed.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Lockit123
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=WFxnwnF7G2F5

  wordpress:
    build: "wordpress.docker"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=WFxnwnF7G2F5

  secret:
    build: "secret.docker"
    ports:
      - "2222:22"



